// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/checkpoint" | "/dashboard" | "/logs" | "/monitoring" | "/rooms" | "/users"
type AppRouteHandlerRoutes = "/api/auth/[...all]" | "/api/logs" | "/api/monitoring" | "/api/movements" | "/api/movements/[movementId]/arrive" | "/api/movements/[movementId]/complete" | "/api/movements/[movementId]/return" | "/api/movements/dispatch" | "/api/register" | "/api/reports/summary" | "/api/session" | "/api/setup/bootstrap" | "/api/users" | "/api/users/[userId]" | "/api/users/[userId]/password" | "/api/wbps" | "/api/wbps/[registrationNumber]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/auth/[...all]": { "all": string[]; }
  "/api/logs": {}
  "/api/monitoring": {}
  "/api/movements": {}
  "/api/movements/[movementId]/arrive": { "movementId": string; }
  "/api/movements/[movementId]/complete": { "movementId": string; }
  "/api/movements/[movementId]/return": { "movementId": string; }
  "/api/movements/dispatch": {}
  "/api/register": {}
  "/api/reports/summary": {}
  "/api/session": {}
  "/api/setup/bootstrap": {}
  "/api/users": {}
  "/api/users/[userId]": { "userId": string; }
  "/api/users/[userId]/password": { "userId": string; }
  "/api/wbps": {}
  "/api/wbps/[registrationNumber]": { "registrationNumber": string; }
  "/checkpoint": {}
  "/dashboard": {}
  "/logs": {}
  "/monitoring": {}
  "/rooms": {}
  "/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
